# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function calculates inverse of matrix of complex variables
#'
#' The function accepts a square complex matrix and returns inverse of it.
#'
#' @param x The square matrix of complex variables.
#'
#' @template author
#'
#' @return The function returns a matrix of the same size as the original
#' matrix \code{x}
#'
#' @seealso \link[base]{solve}
#'
#' @examples
#'
#' invert(matrix(complex(real=c(1,2), imaginary=c(1.1,2.1)), 2, 2))
#'
#' @useDynLib complex
#' @export
invert <- function(x) {
    .Call('_complex_invert', PACKAGE = 'complex', x)
}

polyprodcomplex <- function(poly1, poly2) {
    .Call('_complex_polyprodcomplex', PACKAGE = 'complex', poly1, poly2)
}

